sudo: false
language: node_js
node_js:
  - "10"

services:
  - docker

script:
  - npm test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t coredns-admin .
  - docker tag coredns-admin $DOCKER_USERNAME/coredns-admin
  - docker tag coredns-admin $DOCKER_USERNAME/coredns-admin
  - docker push $DOCKER_USERNAME/coredns-admin 
  - docker images