log:
  # http log format
  http: :method :url :status :length :response-time ms ":referrer"
  level: info
# 程序监控端口
port: 5018
# 程序url前缀
appPrefix: /coredns
# mongodb连接串
mongo: mongodb://127.0.0.1/coredns?connectTimeoutMS=10000
adminPath: /admin
cookieSigKeys:
  - cuttle-fish
  - tree.xie
dns:
  freshInterval: 0 
coredns:
  # coredns中使用的etcd
  etcd: 192.168.31.3:2371,192.168.31.3:2372,192.168.31.3:2373
  path: /coredns
